Added support for different icons - take 2
ngnijland/MMM-social-counter pull request #6
Opened 2020-09-12 18:21 UTC by adi-miller

Specifically, I wanted to be able to use the fa-twitter-square icon. So added support to just specify the name of the icon. If missing from the configuration, the default is fa-twitter.

2020-09-18 20:04 UTC, adi-miller commented
Ping...?

2020-09-19 14:10 UTC, ngnijland commented
Sorry @adi-miller, I layed sick in bed all week. I will review your PR now, thanks for the contribution!

2020-09-19 14:12 UTC, ngnijland requested changes

2020-09-19 14:12 UTC, ngnijland commented on MMM-social-counter.js
> +    this.icon = this.config.icon || 'fa-twitter';
I'd rather have all default values in one overview at the `defaults` object at the top of this file. Can you move this please?

2020-09-19 14:12 UTC, ngnijland commented on README.md
> +`icon`                | `string                    | `fa-twitter`  | The font name (from FontAwesome) to display next to the follower count, e.g. fa-twitter-square
I think this is a typo?

`The font name` -> `The icon name`

2020-09-19 19:49 UTC, closed without merging

2020-09-19 19:49 UTC, adi-miller commented
Submitting a new PR with fixes.